### PR TITLE
Add checkboxes

### PR DESCRIPTION
**Pull request by sanket-dm**
Added checked and unchecked boxes.

### CODE REVIEW

**Comment by samrobbins85** [comment]
Thanks for this. Not quite sure what you're trying to do with the slash, you can see [here](https://initoss-pivwafy3y.vercel.app/learn_code/Markdown/5-Listsl) it just appears as the slash character.

**Comment by sanket-dm** [comment]
Yea, i just wanted to seperate the two lines. Putting the content after the slash in a new line. 
In markdown, it shows as two seperate lines though but in the website it just appears as a slash.
Maybe you can edit the commit such that it displays the format well because I dont know much about javascript (on which the website is based on).
Anyways, thanks!

**Comment by samrobbins85** [comment]
Yeah it can get confusing with all the slightly different markdown specifications, what was needed here was to add in a blank line

**Comment by sanket-dm** [comment]
Thanks :)

**Pull request merged**
